package secure_pacs_simulator;

import java.awt.Dialog;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import static secure_pacs_simulator.Client.getLFSR_key;
import static secure_pacs_simulator.Client.login;

public class Client_user extends javax.swing.JFrame {
    
    String username = null;
//    Long EncryptedDICOMTransferTime;

    
    public Client_user() {
        initComponents();
        

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtUsername = new javax.swing.JTextField();
        jBtnAthenticate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaUserInfo = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jBtnViewDicomImg = new javax.swing.JButton();
        listDicomFile = new java.awt.List();
        jButton5 = new javax.swing.JButton();
        jLbStatus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLbEncryptedLFSRKeyTransferTime = new javax.swing.JLabel();
        jLbLFSRKeyDecryptedTime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLbEncryptedDICOMTransferTime = new javax.swing.JLabel();
        jLbDICOMEncryptTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Users Panel");

        jLabel1.setText("Username");

        jBtnAthenticate.setText("Authenticate");
        jBtnAthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAthenticateActionPerformed(evt);
            }
        });

        jTextAreaUserInfo.setColumns(20);
        jTextAreaUserInfo.setLineWrap(true);
        jTextAreaUserInfo.setRows(5);
        jTextAreaUserInfo.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaUserInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAthenticate)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAthenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Decryption"));

        jLabel6.setText("DICOM File:");

        jBtnViewDicomImg.setText("View Dicom File");
        jBtnViewDicomImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnViewDicomImgActionPerformed(evt);
            }
        });

        listDicomFile.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listDicomFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnViewDicomImg)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listDicomFile, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnViewDicomImg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        jButton5.setText("X");

        jLbStatus.setText("Waiting.....");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Decrypted LFSR Key Time (Millsec):");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Encrypted LFSR Key Transfer Time (Millsec):");

        jLbEncryptedLFSRKeyTransferTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbEncryptedLFSRKeyTransferTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLbLFSRKeyDecryptedTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbLFSRKeyDecryptedTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("DICOM File Decryption Time (Millsec):");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Encrypted DICOM File Transfer Time (Millsec):");

        jLbEncryptedDICOMTransferTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbEncryptedDICOMTransferTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLbDICOMEncryptTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbDICOMEncryptTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbLFSRKeyDecryptedTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbEncryptedDICOMTransferTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbDICOMEncryptTime, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jLbEncryptedLFSRKeyTransferTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(308, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbEncryptedLFSRKeyTransferTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLbLFSRKeyDecryptedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLbEncryptedDICOMTransferTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLbDICOMEncryptTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addContainerGap(159, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5))
                    .addComponent(jPanel1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLbStatus))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName(" User ");
        jPanel2.getAccessibleContext().setAccessibleName("Data Decryption ");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
       
    private void jBtnAthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAthenticateActionPerformed
        // TODO add your handling code here:
        if(jTxtUsername.getText() == null || jTxtUsername.getText().isEmpty() || jTxtUsername.getText().isBlank()){
            JOptionPane optionPane = new JOptionPane("Username cannot be empty!",JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Error!");
            dialog.setAlwaysOnTop(true); // to show top of all other application
            dialog.setVisible(true); // to visible the dialog
            jTxtUsername.grabFocus();
        }else{
            try {
                //        String[] myinfo = login();
                SQLiteDBSystem db = new SQLiteDBSystem();
                db.connect();
                String myUsername = jTxtUsername.getText();
                String[] myinfo = db.SelectUser(myUsername);
                
                //        ArrayList<String> info = new ArrayList();
                //        info.addAll(Arrays.asList(myinfo));
                String string = "Username: "+ myinfo[0] +"\n";
                string += "Secret key: "+ myinfo[2] +"\n";
                string += "Public key: "+ myinfo[3] +"\n";
                //        System.out.printf("%s \t %s \n", "Password: ", myinfo[1]);
                //        System.out.printf("%s \t %s \n", "Secret key: ", myinfo[2]);
                //        System.out.printf("%s \t %s \n", "Public key: ", myinfo[3]);
                jTextAreaUserInfo.setText(string);


                ArrayList<String> datainfo = db.getBinaryFileNamesFromDatabase();
                for (String datainfo1 : datainfo) {
                    listDicomFile.add(datainfo1);
                }
                username = myUsername;
                Long start = System.currentTimeMillis();
            } catch (SQLException ex) {
                Logger.getLogger(Client_user.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Client_user.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jBtnAthenticateActionPerformed
    
    //Used in the View Dicom FIle Button
    public static String getDecryptedLFSRKey(String cipher, String username) throws Exception{
        
        String priv_key_filename = "RSA/"+username+"privateKey";
        String privateKey = Base64.getEncoder().encodeToString(RSAAlgorithm.readPriKeyFromFile(priv_key_filename));
        String decryptedString = RSAAlgorithm.decrypt(cipher, privateKey);
        System.out.println(decryptedString);
//        RSA rsa_d = new RSA(cipher);             
//        String decrypted_key = rsa_d.decrypt(pri_key_filename);        
//        System.out.printf("%s \t %s \n", "Encrypted LFSR key: ", decrypted_key);
        return decryptedString;
    }
    

    
    public void decrypt_dicom_file(int fid, String lfsr_dec_key) throws SQLException, IOException{
       String dcr_dicom_file_name = null;
       SQLiteDBSystem db = new SQLiteDBSystem();
       db.connect();
       
       Long start_3 = System.currentTimeMillis(); 

       String enc_dicom_file_name = db.SelectBinarydata(fid);
       
       Long time_3 = System.currentTimeMillis() - start_3;
       
//       this.EncryptedDICOMTransferTime = time_3;
       jLbEncryptedDICOMTransferTime.setText(""+time_3);
             
       AESAlgorithm aes = new AESAlgorithm();
        try {
            
            Long start_4 = System.currentTimeMillis(); 
            String fileName = enc_dicom_file_name.substring(0, enc_dicom_file_name.lastIndexOf("."));
            fileName = "decrypted"+fileName;
            dcr_dicom_file_name = AESAlgorithm.decryptFile(enc_dicom_file_name, fileName, lfsr_dec_key);
            
            Long time_4 = System.currentTimeMillis() - start_3;
            
            jLbDICOMEncryptTime.setText(" "+time_4);
            System.out.println(dcr_dicom_file_name);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
       String fName = "case2a_001_test2.dcm";
       DicomViewScrollAndWindowWidthAndLeveling dicom_view = new DicomViewScrollAndWindowWidthAndLeveling();
       DicomViewScrollAndWindowWidthAndLeveling.showImage(dcr_dicom_file_name);
//        DicomViewScrollAndWindowWidthAndLeveling.showImage(fName);

       
    }
    
    
    private void jBtnViewDicomImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnViewDicomImgActionPerformed

       String item = listDicomFile.getSelectedItem();       
       
       int fid = Integer.parseInt((item.split("\\|")[1]).trim().strip());
       jLbStatus.setText("File ID: "+ fid);
       
       SQLiteDBSystem db = new SQLiteDBSystem();
       db.connect();


       Long start = System.currentTimeMillis();
      
      String encrypted_lfsr_key = db.SelectEncryptedLFSRKey(fid, username);
      
      Long time = System.currentTimeMillis() - start;
      jLbEncryptedLFSRKeyTransferTime.setText(""+ time);
      
      jLbEncryptedLFSRKeyTransferTime.setText(""+ 1);
       jLbStatus.setText("Encrypted LFSR fetched... ");     
//       System.out.print(Arrays.toString(lfsr_byte));
        try {
            
            Long start_2 = System.currentTimeMillis();     
            System.out.printf("GGGGGGGGGGGGG %s", encrypted_lfsr_key);
            String lfsr_dec = getDecryptedLFSRKey(encrypted_lfsr_key, username);
            
//            System.out.println(lfsr_dec);
            Long time_2 = System.currentTimeMillis() - start_2;
            
            jLbLFSRKeyDecryptedTime.setText(""+ time_2);
            

            decrypt_dicom_file(fid, lfsr_dec);

//            jLbEncryptedDICOMTransferTime.setText(""+EncryptedDICOMTransferTime);
        } catch (Exception ex) {
            Logger.getLogger(Client_user.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jBtnViewDicomImgActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_user().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAthenticate;
    private javax.swing.JButton jBtnViewDicomImg;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbDICOMEncryptTime;
    private javax.swing.JLabel jLbEncryptedDICOMTransferTime;
    private javax.swing.JLabel jLbEncryptedLFSRKeyTransferTime;
    private javax.swing.JLabel jLbLFSRKeyDecryptedTime;
    private javax.swing.JLabel jLbStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaUserInfo;
    private javax.swing.JTextField jTxtUsername;
    private java.awt.List listDicomFile;
    // End of variables declaration//GEN-END:variables
    
}
